/* Spike: minimal hand-written bare-metal nRF52840 blink (LED1 = P0.13).
 *
 * This is NOT generated by silicac — it is a throwaway artifact to validate the
 * target environment (arm-none-eabi toolchain + Renode + the nRF52840 GPIO
 * model) before the on-metal backend is built.  It mirrors what the metal
 * backend will eventually emit: a vector table, a reset handler, and volatile
 * MMIO register access — exactly the shapes `SirPlace::Reg` lowers to.
 */
#include <stdint.h>

/* nRF52840 GPIO port P0 @ 0x5000_0000 (§ scope doc). */
#define P0_BASE     0x50000000UL
#define GPIO_OUTSET (*(volatile uint32_t *)(P0_BASE + 0x508)) /* write-1-to-set  */
#define GPIO_OUTCLR (*(volatile uint32_t *)(P0_BASE + 0x50C)) /* write-1-to-clear */
#define GPIO_DIRSET (*(volatile uint32_t *)(P0_BASE + 0x518))

#define LED_PIN 13 /* PCA10056 DK LED1, active-low */

extern uint32_t _estack;
void Reset_Handler(void);

/* Minimal Cortex-M vector table: [0]=initial SP, [1]=reset.  The remaining
 * system/IRQ entries are unused by the spike (it never faults or takes an IRQ).
 * Placed at flash base by the linker script. */
__attribute__((section(".vectors"), used))
const void *const vectors[] = {
    (void *)&_estack,
    (void *)Reset_Handler,
};

static void delay(volatile uint32_t n) {
    while (n--) {
        __asm__ volatile("nop");
    }
}

void Reset_Handler(void) {
    GPIO_DIRSET = (1UL << LED_PIN); /* drive P0.13 as output */
    for (;;) {
        GPIO_OUTCLR = (1UL << LED_PIN); /* LED on  (active-low) */
        delay(400000);
        GPIO_OUTSET = (1UL << LED_PIN); /* LED off */
        delay(400000);
    }
}
