/* Generated by silicac — do not edit.  Freestanding metal target (§6.2/§6.4). */
#include <stdint.h>

/* Memory barriers (§4.2/§6.2): ordered MMIO + DMA/IRQ hand-off. */
#define __DSB() __asm__ volatile("dsb 0xf" ::: "memory")
#define __DMB() __asm__ volatile("dmb 0xf" ::: "memory")
#define __ISB() __asm__ volatile("isb 0xf" ::: "memory")

/* BASEPRI access for priority-ceiling critical sections (§5.5). */
#define __set_BASEPRI(v) __asm__ volatile("msr basepri, %0" :: "r"((uint32_t)(v)) : "memory")
static inline uint32_t __get_BASEPRI(void) { uint32_t __r; __asm__ volatile("mrs %0, basepri" : "=r"(__r)); return __r; }

/* Symbols provided by the generated linker script (§6.4). */
extern uint32_t _estack;
extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss;

/* program variables and cells */
static volatile uint32_t v = 0ULL; /* cell */


/* Safe-state drive (§5.6): bounded, non-yielding register writes. */
static void __drive_safe(void) {
}

/* §4.3 width-checked integer arithmetic (SIL-004): plain +/-/* trap on */
/* overflow; `+%`-family wrap, `+|`-family saturate, at the target width. */
static void __silica_overflow_trap(void) {
    __asm__ volatile("cpsid i" ::: "memory"); /* overflow → halt */
    __drive_safe();
    for (;;) { __asm__ volatile("wfi"); } /* hold in safe state (§4.3) */
}
static inline uint32_t __si_add_trap_u32(uint32_t a, uint32_t b) { uint32_t __r; if (__builtin_add_overflow(a, b, &__r)) __silica_overflow_trap(); return __r; }

/* reaction: on sys.start */
static void __reaction_0(void) {
    { /* critical-section: raise to ceiling 1 (BASEPRI 0x20) */
        uint32_t __bp_saved = __get_BASEPRI();
        __set_BASEPRI(0x20U);
        __ISB();
        v = 1ULL;
        __DMB();
        __set_BASEPRI(__bp_saved);
    }
}

/* reaction: every 100000000ns */
static void __reaction_1(void) {
    { /* critical-section: raise to ceiling 1 (BASEPRI 0x20) */
        uint32_t __bp_saved = __get_BASEPRI();
        __set_BASEPRI(0x20U);
        __ISB();
        v = __si_add_trap_u32(v, 1ULL);
        __DMB();
        __set_BASEPRI(__bp_saved);
    }
}


/* default handler for unused vectors */
static void __default_handler(void) { for (;;) {} }
void Reset_Handler(void);

/* Layer-3 fault decoder: address-ownership map (§5.4) */
#define __OWNER_COUNT 2U
static const uint32_t __owner_start[__OWNER_COUNT] = { 0x00000000U, 0x20000000U };
static const uint32_t __owner_end[__OWNER_COUNT]   = { 0x00100000U, 0x20040000U };
/* owner[0] = flash [0x00000000, 0x00100000) */
/* owner[1] = ram [0x20000000, 0x20040000) */
/* Layer-3 site map: PC -> (handler, when-state) (§5.4/§7.2, P7-4a) */
#define __SITE_COUNT 2U
static void (* const __site_fn[__SITE_COUNT])(void) = { __reaction_0, __reaction_1 };
static const uint32_t __site_rid[__SITE_COUNT] = { 0U, 1U };
/* site[0] = __reaction_0 [sys.start] when { any } */
/* site[1] = __reaction_1 [every 100000000ns] when { any } */
/* fault record (read by the host decoder) — structured, no strings (§4.3) */
volatile uint32_t __fault_addr = 0U;
volatile uint32_t __fault_owner = 0xFFFFFFFFUL; /* index, or 0xFFFFFFFF = unclaimed/invalid */
volatile uint32_t __fault_cfsr = 0U;
volatile uint32_t __fault_pending = 0U;
void HardFault_Handler(void) {
    uint32_t __cfsr = *(volatile uint32_t *)0xE000ED28UL; /* SCB CFSR */
    uint32_t __a = 0U;
    uint32_t __o = 0xFFFFFFFFUL;
    if (__cfsr & 0x00008000UL) { /* BFARVALID */
        __a = *(volatile uint32_t *)0xE000ED38UL; /* SCB BFAR */
        for (uint32_t __i = 0U; __i < __OWNER_COUNT; __i++) {
            if (__a >= __owner_start[__i] && __a < __owner_end[__i]) { __o = __i; break; }
        }
    }
    __fault_addr = __a; __fault_owner = __o; __fault_cfsr = __cfsr; __fault_pending = 1U;
    for (;;) { /* halt; safe-state drive is a later phase (§5.6) */ }
}

/* every -> TIMER1 compare dispatch (§4.5, 1us ticks, exact period) */
void TIMER1_IRQHandler(void) {
    if (*(volatile uint32_t *)0x40009140UL != 0U) {
        *(volatile uint32_t *)0x40009140UL = 0U; /* clear EVENTS_COMPARE[0] */
        __DSB();
        *(volatile uint32_t *)0x40009540UL = (*(volatile uint32_t *)0x40009540UL + 100000UL); /* CC[0] += period (re-arm) */
        __reaction_1();
    }
}

/* Cortex-M vector table — placed at flash base by the linker (§6.4). */
__attribute__((section(".vectors"), used))
const void *const __vectors[] = {
    (void *)&_estack,            /* 0  initial SP */
    (void *)&Reset_Handler,      /* 1  reset */
    (void *)&__default_handler,  /* 2  NMI */
    (void *)&HardFault_Handler,  /* 3  HardFault */
    0,                           /* 4  reserved */
    0,                           /* 5  reserved */
    0,                           /* 6  reserved */
    0,                           /* 7  reserved */
    0,                           /* 8  reserved */
    0,                           /* 9  reserved */
    0,                           /* 10  reserved */
    (void *)&__default_handler,  /* 11 SVCall */
    0,                           /* 12 */
    0,                           /* 13 */
    (void *)&__default_handler,  /* 14 PendSV */
    (void *)&__default_handler,  /* 15 SysTick (retired, P6-6) */
    (void *)&__default_handler,  /* 16 IRQ0 */
    (void *)&__default_handler,  /* 17 IRQ1 */
    (void *)&__default_handler,  /* 18 IRQ2 */
    (void *)&__default_handler,  /* 19 IRQ3 */
    (void *)&__default_handler,  /* 20 IRQ4 */
    (void *)&__default_handler,  /* 21 IRQ5 */
    (void *)&__default_handler,  /* 22 IRQ6 */
    (void *)&__default_handler,  /* 23 IRQ7 */
    (void *)&__default_handler,  /* 24 IRQ8 */
    (void *)&TIMER1_IRQHandler,  /* 25 TIMER1 (every) */
};

void Reset_Handler(void) {
    /* copy .data (flash LMA -> RAM VMA) */
    uint32_t *src = &_sidata, *dst = &_sdata;
    while (dst < &_edata) { *dst++ = *src++; }
    /* zero .bss */
    for (dst = &_sbss; dst < &_ebss; ) { *dst++ = 0U; }

    /* run sys.start reactions, in declaration order */
    __reaction_0();

    /* TIMER1: 1MHz free-running, one compare channel per `every` (§4.5) */
    *(volatile uint32_t *)0x40009504UL = 0UL; /* MODE = Timer */
    *(volatile uint32_t *)0x40009508UL = 3UL; /* BITMODE = 32-bit */
    *(volatile uint32_t *)0x40009510UL = 4UL; /* PRESCALER (16MHz>>4 = 1MHz) */
    *(volatile uint32_t *)0x4000900cUL = 1UL; /* TASKS_CLEAR */
    *(volatile uint32_t *)0x40009540UL = 100000UL; /* CC[0] = period (ticks) */
    *(volatile uint32_t *)0x40009304UL = 0x10000UL; /* INTENSET: COMPARE[0..] */
    *(volatile uint8_t *)0xe000e409UL = 0x20U; /* NVIC IPR IRQ9 (TIMER1) priority */
    *(volatile uint32_t *)0xE000E100UL = 0x200UL; /* NVIC ISER0: enable TIMER1 (IRQ9) */
    *(volatile uint32_t *)0x40009000UL = 1UL; /* TASKS_START */

    __DSB();
    __asm__ volatile("cpsie i"); /* enable interrupts */
    __ISB();

    for (;;) { __asm__ volatile("wfi"); }
}
