//! C backend — lowers SIR to a freestanding C source file.
//!
//! Design constraints (§6.2):
//!   - Fixed-width types only (`uint32_t`, `uint8_t`, etc.) — never bare `int`.
//!   - Explicit checked arithmetic (no reliance on signed-overflow UB).
//!   - No C bitfields.
//!   - Explicit barriers where needed.
//!   - No libc beyond what the host target explicitly needs (`stdio.h` for
//!     host_io, `time.h` / `unistd.h` for the `every` timer).
//!
//! Output is a single `.c` file.  The caller invokes `cc` to compile it.

use std::fmt::Write;

use crate::sir::*;

// ─── Entry point ─────────────────────────────────────────────────────────────

pub struct CBackend {
    buf: String,
    indent: usize,
}

impl CBackend {
    pub fn new() -> Self {
        CBackend { buf: String::new(), indent: 0 }
    }

    /// Emit a complete C translation unit from a `SirModule` and return it as
    /// a `String`.
    pub fn emit(mut self, module: &SirModule) -> String {
        self.emit_header(module);
        self.emit_newline();
        self.emit_globals(module);
        self.emit_newline();
        self.emit_reaction_fns(module);
        self.emit_newline();
        self.emit_main(module);
        self.buf
    }

    // ── Preamble ─────────────────────────────────────────────────────────────

    fn emit_header(&mut self, module: &SirModule) {
        // Conditionally include host-only headers.  The scans must recurse into
        // nested statements: after cell analysis, intrinsics / `exit` can be
        // wrapped inside `Critical` (and `If`) bodies, so a top-level-only scan
        // would miss required includes and emit C that won't compile.
        let needs_stdio = module
            .reactions
            .iter()
            .any(|r| any_stmt(&r.body, &stmt_uses_stdio));
        let needs_timer = module.reactions.iter().any(|r| {
            matches!(r.trigger, SirTrigger::EveryNs(_))
        });
        let needs_exit = module
            .reactions
            .iter()
            .any(|r| any_stmt(&r.body, &|s| matches!(s, SirStmt::Exit(_))));

        self.line("/* Generated by silicac — do not edit.  §6.2 freestanding-C subset. */");
        // Request POSIX.1-2008 when we use nanosleep / clock_gettime / struct
        // timespec.  This must appear before any system header.
        if needs_timer {
            self.line("#define _POSIX_C_SOURCE 200809L");
        }
        self.line("#include <stdint.h>");

        if needs_stdio {
            self.line("#include <stdio.h>");
        }
        if needs_timer {
            self.line("#include <time.h>");
        }
        if needs_exit {
            self.line("#include <stdlib.h>");
        }
        if needs_stdio || needs_timer {
            self.line("");
            self.line("/* host_io intrinsic — §7.1 mock device */");
            self.line("static void __host_io_print(const uint8_t *s, uint32_t len) {");
            self.line("    /* fwrite/size_t are C library interface types, not SIR types (§6.2) */");
            self.line("    fwrite(s, 1U, (size_t)len, stdout);");
            self.line("}");
        }
        if needs_timer {
            self.line("");
            self.line("/* nanosleep helper — C library wrapper; time_t/long are POSIX interface types */");
            self.line("static void __host_sleep_ns(uint64_t ns) {");
            self.line("    struct timespec __ts;");
            self.line("    __ts.tv_sec  = (time_t)(ns / UINT64_C(1000000000));");
            self.line("    __ts.tv_nsec = (long)(ns % UINT64_C(1000000000));");
            self.line("    nanosleep(&__ts, (struct timespec *)0);");
            self.line("}");
            self.line("");
            self.line("/* monotonic-time helper — host target; §4.5/D15 fixed-rate scheduling */");
            self.line("static uint64_t __get_mono_ns(void) {");
            self.line("    struct timespec __ts;");
            self.line("    clock_gettime(CLOCK_MONOTONIC, &__ts);");
            self.line("    /* tv_sec/tv_nsec: POSIX interface types, cast to fixed-width (§6.2) */");
            self.line("    return (uint64_t)__ts.tv_sec * UINT64_C(1000000000)");
            self.line("         + (uint64_t)__ts.tv_nsec;");
            self.line("}");
        }
    }

    // ── Global variables (cells) ──────────────────────────────────────────────

    fn emit_globals(&mut self, module: &SirModule) {
        if module.vars.is_empty() {
            return;
        }
        self.line("/* program variables and cells */");
        for var in &module.vars {
            let c_ty = var.ty.c_type();
            let c_init = expr_to_c_literal(&var.init);
            let comment = if var.is_cell { " /* cell */" } else { "" };
            let decl = format!("static {} {} = {};{}", c_ty, var.name, c_init, comment);
            self.line(&decl);
        }
        self.emit_newline();
    }

    // ── Reaction functions ────────────────────────────────────────────────────

    fn emit_reaction_fns(&mut self, module: &SirModule) {
        for reaction in &module.reactions {
            self.emit_reaction_fn(reaction);
            self.emit_newline();
        }
    }

    fn emit_reaction_fn(&mut self, reaction: &SirReaction) {
        let fn_name = reaction_fn_name(reaction.id);
        let comment = trigger_comment(&reaction.trigger);
        self.line(&format!("/* {} */", comment));
        self.line(&format!("static void {}(void) {{", fn_name));
        self.indent += 1;
        for stmt in &reaction.body {
            self.emit_stmt(stmt);
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_stmt(&mut self, stmt: &SirStmt) {
        match stmt {
            SirStmt::Intrinsic(intr) => self.emit_intrinsic(intr),
            SirStmt::Assign { target, value } => match target {
                SirPlace::Var(name) => {
                    let val = emit_expr(value);
                    self.line(&format!("{} = {};", name, val));
                }
                SirPlace::Reg { device, reg_offset, .. } => {
                    // The MMIO-lowering metal backend is deferred (Phase 3);
                    // the slice exercises register access through the host
                    // simulator (`--sim`), which services the same SIR node.
                    self.line(&format!(
                        "/* TODO(metal): MMIO store to device {} reg 0x{:x} */",
                        device, reg_offset
                    ));
                }
            },
            SirStmt::If { cond, then } => {
                let c = emit_expr(cond);
                self.line(&format!("if ({}) {{", c));
                self.indent += 1;
                for s in then {
                    self.emit_stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            SirStmt::Critical { ceiling, body } => {
                // Metal lowers `ceiling` to a BASEPRI raise/restore (§5.5).  On
                // the host C path there is nothing to mask; keep the section
                // visible as a comment and emit the body.
                self.line(&format!("/* critical-section enter (ceiling {}) */", ceiling));
                for s in body {
                    self.emit_stmt(s);
                }
                self.line("/* critical-section exit */");
            }
            SirStmt::DeviceOp { device, op, .. } => {
                self.line(&format!("/* TODO(metal): device {} op {} */", device, op));
            }
            SirStmt::Exit(code) => {
                let c = emit_expr(code);
                self.line(&format!("exit((int)({}));", c));
            }
        }
    }

    fn emit_intrinsic(&mut self, intr: &SirIntrinsic) {
        match intr {
            SirIntrinsic::HostIoPrintStr(s) => {
                // Emit a string as a static byte array, then call __host_io_print.
                // Escape the string for C.
                let escaped = c_escape_bytes(s.as_bytes());
                let len = s.len();
                let line = format!(
                    "__host_io_print((const uint8_t *)\"{}\" , {}U);",
                    escaped, len
                );
                self.line(&line);
            }
            SirIntrinsic::HostIoPrint(expr) => {
                // Generic: requires a (ptr, len) pair.  In Phase 0 only Bytes
                // literals reach here.
                match expr {
                    SirExpr::Bytes(bytes) => {
                        let escaped = c_escape_bytes(bytes);
                        let len = bytes.len();
                        let line = format!(
                            "__host_io_print((const uint8_t *)\"{}\" , {}U);",
                            escaped, len
                        );
                        self.line(&line);
                    }
                    _ => {
                        // Variable-length bytes — emit a helper call.
                        let e = emit_expr(expr);
                        self.line(&format!("/* TODO: dynamic bytes print: {} */", e));
                    }
                }
            }
            SirIntrinsic::HostIoFlush => {
                self.line("fflush(stdout);");
            }
        }
    }

    // ── main() ────────────────────────────────────────────────────────────────

    fn emit_main(&mut self, module: &SirModule) {
        self.line("int main(void) {");
        self.indent += 1;

        // 1. Fire all SysStart reactions first (they run before the event loop).
        for reaction in &module.reactions {
            if matches!(reaction.trigger, SirTrigger::SysStart) {
                let call = format!("{}();", reaction_fn_name(reaction.id));
                self.line(&call);
            }
        }

        // 2. If there are no periodic reactions, we're done.
        let periodic: Vec<(usize, u64)> = module.reactions.iter()
            .filter_map(|r| if let SirTrigger::EveryNs(ns) = r.trigger {
                Some((r.id, ns))
            } else {
                None
            })
            .collect();

        if !periodic.is_empty() {
            self.emit_newline();

            // Declare one deadline variable per periodic reaction at function
            // scope so they survive across loop iterations.  Initialise each to
            // now + period (first fire time).
            //
            // Fixed-rate scheduling (§4.5/D15): the next deadline is always
            // advanced by the period from the *scheduled* time, not from when
            // the handler returns, so handler execution time does not accumulate
            // as drift.  Overruns are coalesced (§4.5/D15): if a handler misses
            // one or more ticks the scheduler drops them and advances to the
            // next future deadline rather than queueing catch-up firings.
            self.line("/* fixed-rate deadline tracking — §4.5/D15 */");
            for (id, ns) in &periodic {
                self.line(&format!(
                    "uint64_t __deadline_{} = __get_mono_ns() + {}ULL;",
                    id, ns
                ));
            }

            self.emit_newline();
            self.line("/* event loop */");
            self.line("for (;;) {");
            self.indent += 1;

            // Sleep until the nearest upcoming deadline.
            self.line("uint64_t __now = __get_mono_ns();");
            self.line("uint64_t __sleep_ns = 0ULL;");
            for (id, _) in &periodic {
                self.line(&format!("if (__deadline_{} > __now) {{", id));
                self.indent += 1;
                self.line(&format!("uint64_t __d = __deadline_{} - __now;", id));
                self.line("if (__sleep_ns == 0ULL || __d < __sleep_ns) __sleep_ns = __d;");
                self.indent -= 1;
                self.line("}");
            }
            self.line("if (__sleep_ns > 0ULL) __host_sleep_ns(__sleep_ns);");

            self.emit_newline();
            // Fire all due reactions; advance each deadline (coalescing overruns).
            self.line("__now = __get_mono_ns();");
            for (id, ns) in &periodic {
                self.line(&format!("if (__now >= __deadline_{}) {{", id));
                self.indent += 1;
                self.line(&format!("{}();", reaction_fn_name(*id)));
                // Advance by period until the deadline is in the future.
                // This drops any missed ticks (coalesce — §4.5/D15).
                self.line(&format!(
                    "do {{ __deadline_{} += {}ULL; }} while (__deadline_{} <= __now);",
                    id, ns, id
                ));
                self.indent -= 1;
                self.line("}");
            }

            self.indent -= 1;
            self.line("}");
        } else {
            self.line("return 0;");
        }

        self.indent -= 1;
        self.line("}");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    fn line(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.buf.push_str(&indent);
        self.buf.push_str(s);
        self.buf.push('\n');
    }

    fn emit_newline(&mut self) {
        self.buf.push('\n');
    }
}

// ─── Free helpers ─────────────────────────────────────────────────────────────

fn reaction_fn_name(id: usize) -> String {
    format!("__reaction_{}", id)
}

/// Does any statement in `stmts` (recursing into `Critical`/`If` bodies)
/// satisfy `pred`?
fn any_stmt(stmts: &[SirStmt], pred: &dyn Fn(&SirStmt) -> bool) -> bool {
    stmts.iter().any(|s| {
        pred(s)
            || match s {
                SirStmt::Critical { body, .. } => any_stmt(body, pred),
                SirStmt::If { then, .. } => any_stmt(then, pred),
                _ => false,
            }
    })
}

fn stmt_uses_stdio(s: &SirStmt) -> bool {
    matches!(
        s,
        SirStmt::Intrinsic(SirIntrinsic::HostIoPrint(_))
            | SirStmt::Intrinsic(SirIntrinsic::HostIoPrintStr(_))
            | SirStmt::Intrinsic(SirIntrinsic::HostIoFlush)
    )
}

fn trigger_comment(trigger: &SirTrigger) -> String {
    match trigger {
        SirTrigger::SysStart => "reaction: on sys.start".into(),
        SirTrigger::EveryNs(ns) => format!("reaction: every {}ns", ns),
        SirTrigger::Event(id) => format!("reaction: on event {}", id),
    }
}

fn emit_expr(expr: &SirExpr) -> String {
    match expr {
        SirExpr::Bool(b) => if *b { "1U".into() } else { "0U".into() },
        SirExpr::U64(n) => format!("{}ULL", n),
        SirExpr::Bytes(bytes) => {
            // Bytes as a cast-to-const-pointer string literal.
            let escaped = c_escape_bytes(bytes);
            format!("(const uint8_t *)\"{}\"", escaped)
        }
        SirExpr::Load(name) => name.clone(),
        SirExpr::RegLoad { device, reg_offset, .. } => {
            format!("0U /* TODO(metal): MMIO load device {} reg 0x{:x} */", device, reg_offset)
        }
        SirExpr::Not(inner) => format!("(!({}))", emit_expr(inner)),
        SirExpr::BinOp(op, lhs, rhs) => {
            let l = emit_expr(lhs);
            let r = emit_expr(rhs);
            let op_str = match op {
                SirBinOp::Add => "+",
                SirBinOp::Sub => "-",
                SirBinOp::Mul => "*",
                SirBinOp::Div => "/",
                SirBinOp::Rem => "%",
                SirBinOp::And => "&&",
                SirBinOp::Or => "||",
                SirBinOp::EqEq => "==",
                SirBinOp::NotEq => "!=",
                SirBinOp::Lt => "<",
                SirBinOp::Le => "<=",
                SirBinOp::Gt => ">",
                SirBinOp::Ge => ">=",
            };
            format!("({} {} {})", l, op_str, r)
        }
    }
}

fn expr_to_c_literal(expr: &SirExpr) -> String {
    match expr {
        SirExpr::Bool(b) => if *b { "1U".into() } else { "0U".into() },
        SirExpr::U64(n) => format!("{}ULL", n),
        _ => "0".into(),
    }
}

/// Escape a byte slice into a C string literal body (no surrounding quotes).
fn c_escape_bytes(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len());
    for &b in bytes {
        match b {
            b'\n' => s.push_str("\\n"),
            b'\t' => s.push_str("\\t"),
            b'\r' => s.push_str("\\r"),
            b'\\' => s.push_str("\\\\"),
            b'"' => s.push_str("\\\""),
            0x20..=0x7e => s.push(b as char),
            // Fixed-width 3-digit octal, not `\xNN`: a C `\x` escape greedily
            // consumes *all* following hex digits, so `\xA9` before an ASCII
            // hex digit would merge into one larger value and corrupt the byte
            // stream.  An octal escape consumes at most 3 digits, so emitting
            // exactly 3 is unambiguous regardless of the next character.
            _ => {
                let _ = write!(s, "\\{:03o}", b);
            }
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_escape_basics() {
        assert_eq!(c_escape_bytes(b"Hello\n"), "Hello\\n");
        assert_eq!(c_escape_bytes(b"say \"hi\""), "say \\\"hi\\\"");
    }

    #[test]
    fn c_escape_nonprintable_uses_fixed_octal() {
        // 0xA9 followed by an ASCII hex digit must NOT use `\xNN` (which would
        // greedily merge into one escape).  Fixed 3-digit octal is unambiguous.
        assert_eq!(c_escape_bytes(&[0xA9, b'A']), "\\251A");
        assert_eq!(c_escape_bytes(&[0x00, b'1']), "\\0001");
    }

    #[test]
    fn includes_stdio_for_print_nested_in_critical() {
        // After cell analysis a print can live inside a `Critical` body; the
        // header scan must recurse to still include <stdio.h> + the helper.
        let module = SirModule {
            reactions: vec![SirReaction {
                id: 0,
                trigger: SirTrigger::SysStart,
                body: vec![SirStmt::Critical {
                    ceiling: 1,
                    body: vec![SirStmt::Intrinsic(SirIntrinsic::HostIoPrintStr("hi\n".into()))],
                }],
                priority: 0,
            }],
            ..Default::default()
        };
        let c = CBackend::new().emit(&module);
        assert!(c.contains("#include <stdio.h>"), "missing stdio include for nested print");
        assert!(c.contains("__host_io_print"), "missing host_io helper for nested print");
    }

    #[test]
    fn emit_hello_world() {
        let module = SirModule {
            reactions: vec![SirReaction {
                id: 0,
                trigger: SirTrigger::SysStart,
                body: vec![SirStmt::Intrinsic(SirIntrinsic::HostIoPrintStr(
                    "Hello, World!\n".into(),
                ))],
                priority: 0,
            }],
            ..Default::default()
        };
        let c = CBackend::new().emit(&module);
        assert!(c.contains("__host_io_print"));
        assert!(c.contains("Hello, World!\\n"));
        assert!(c.contains("int main(void)"));
        assert!(c.contains("__reaction_0();"));
    }
}
