//! C backend — lowers SIR to a freestanding C source file.
//!
//! Design constraints (§6.2):
//!   - Fixed-width types only (`uint32_t`, `uint8_t`, etc.) — never bare `int`.
//!   - Explicit checked arithmetic (no reliance on signed-overflow UB).
//!   - No C bitfields.
//!   - Explicit barriers where needed.
//!   - No libc beyond what the host target explicitly needs (`stdio.h` for
//!     host_io, `time.h` / `unistd.h` for the `every` timer).
//!
//! Output is a single `.c` file.  The caller invokes `cc` to compile it.

use std::fmt::Write;

use crate::sir::*;

// ─── Entry point ─────────────────────────────────────────────────────────────

pub struct CBackend {
    buf: String,
    indent: usize,
}

impl CBackend {
    pub fn new() -> Self {
        CBackend { buf: String::new(), indent: 0 }
    }

    /// Emit a complete C translation unit from a `SirModule` and return it as
    /// a `String`.
    pub fn emit(mut self, module: &SirModule) -> String {
        self.emit_header(module);
        self.emit_newline();
        self.emit_globals(module);
        self.emit_newline();
        self.emit_reaction_fns(module);
        self.emit_newline();
        self.emit_main(module);
        self.buf
    }

    // ── Preamble ─────────────────────────────────────────────────────────────

    fn emit_header(&mut self, module: &SirModule) {
        self.line("/* Generated by silicac — do not edit.  §6.2 freestanding-C subset. */");
        self.line("#include <stdint.h>");

        // Conditionally include host-only headers.
        let needs_stdio = module.reactions.iter().any(|r| {
            r.body.iter().any(|s| matches!(s,
                SirStmt::Intrinsic(SirIntrinsic::HostIoPrint(_))
              | SirStmt::Intrinsic(SirIntrinsic::HostIoPrintStr(_))
              | SirStmt::Intrinsic(SirIntrinsic::HostIoFlush)
            ))
        });
        let needs_timer = module.reactions.iter().any(|r| {
            matches!(r.trigger, SirTrigger::EveryNs(_))
        });
        let needs_exit = module.reactions.iter().any(|r| {
            r.body.iter().any(|s| matches!(s, SirStmt::Exit(_)))
        });

        if needs_stdio {
            self.line("#include <stdio.h>");
        }
        if needs_timer {
            self.line("#include <time.h>");
        }
        if needs_exit {
            self.line("#include <stdlib.h>");
        }
        if needs_stdio || needs_timer {
            self.line("");
            self.line("/* host_io intrinsic — §7.1 mock device */");
            self.line("static void __host_io_print(const uint8_t *s, uint32_t len) {");
            self.line("    fwrite(s, 1U, (size_t)len, stdout);");
            self.line("}");
        }
        if needs_timer {
            self.line("");
            self.line("/* nanosleep helper — host timer mock */");
            self.line("static void __host_sleep_ns(uint64_t ns) {");
            self.line("    struct timespec ts;");
            self.line("    ts.tv_sec  = (time_t)(ns / UINT64_C(1000000000));");
            self.line("    ts.tv_nsec = (long)(ns % UINT64_C(1000000000));");
            self.line("    nanosleep(&ts, (struct timespec *)0);");
            self.line("}");
        }
    }

    // ── Global variables (cells) ──────────────────────────────────────────────

    fn emit_globals(&mut self, module: &SirModule) {
        if module.vars.is_empty() {
            return;
        }
        self.line("/* program variables and cells */");
        for var in &module.vars {
            let c_ty = var.ty.c_type();
            let c_init = expr_to_c_literal(&var.init);
            let comment = if var.is_cell { " /* cell */" } else { "" };
            let decl = format!("static {} {} = {};{}", c_ty, var.name, c_init, comment);
            self.line(&decl);
        }
        self.emit_newline();
    }

    // ── Reaction functions ────────────────────────────────────────────────────

    fn emit_reaction_fns(&mut self, module: &SirModule) {
        for reaction in &module.reactions {
            self.emit_reaction_fn(reaction);
            self.emit_newline();
        }
    }

    fn emit_reaction_fn(&mut self, reaction: &SirReaction) {
        let fn_name = reaction_fn_name(reaction.id);
        let comment = trigger_comment(&reaction.trigger);
        self.line(&format!("/* {} */", comment));
        self.line(&format!("static void {}(void) {{", fn_name));
        self.indent += 1;
        for stmt in &reaction.body {
            self.emit_stmt(stmt);
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_stmt(&mut self, stmt: &SirStmt) {
        match stmt {
            SirStmt::Intrinsic(intr) => self.emit_intrinsic(intr),
            SirStmt::Assign { target, value } => {
                let place = emit_place(target);
                let val = emit_expr(value);
                let line = format!("{} = {};", place, val);
                self.line(&line);
            }
            SirStmt::If { cond, then } => {
                let c = emit_expr(cond);
                self.line(&format!("if ({}) {{", c));
                self.indent += 1;
                for s in then {
                    self.emit_stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            SirStmt::Exit(code) => {
                let c = emit_expr(code);
                self.line(&format!("exit((int)({}));", c));
            }
        }
    }

    fn emit_intrinsic(&mut self, intr: &SirIntrinsic) {
        match intr {
            SirIntrinsic::HostIoPrintStr(s) => {
                // Emit a string as a static byte array, then call __host_io_print.
                // Escape the string for C.
                let escaped = c_escape_bytes(s.as_bytes());
                let len = s.len();
                let line = format!(
                    "__host_io_print((const uint8_t *)\"{}\" , {}U);",
                    escaped, len
                );
                self.line(&line);
            }
            SirIntrinsic::HostIoPrint(expr) => {
                // Generic: requires a (ptr, len) pair.  In Phase 0 only Bytes
                // literals reach here.
                match expr {
                    SirExpr::Bytes(bytes) => {
                        let escaped = c_escape_bytes(bytes);
                        let len = bytes.len();
                        let line = format!(
                            "__host_io_print((const uint8_t *)\"{}\" , {}U);",
                            escaped, len
                        );
                        self.line(&line);
                    }
                    _ => {
                        // Variable-length bytes — emit a helper call.
                        let e = emit_expr(expr);
                        self.line(&format!("/* TODO: dynamic bytes print: {} */", e));
                    }
                }
            }
            SirIntrinsic::HostIoFlush => {
                self.line("fflush(stdout);");
            }
        }
    }

    // ── main() ────────────────────────────────────────────────────────────────

    fn emit_main(&mut self, module: &SirModule) {
        self.line("int main(void) {");
        self.indent += 1;

        // 1. Fire all SysStart reactions first (they run before the event loop).
        for reaction in &module.reactions {
            if matches!(reaction.trigger, SirTrigger::SysStart) {
                let call = format!("{}();", reaction_fn_name(reaction.id));
                self.line(&call);
            }
        }

        // 2. If there are no periodic reactions, we're done.
        let has_periodic = module.reactions.iter().any(|r| matches!(r.trigger, SirTrigger::EveryNs(_)));

        if has_periodic {
            self.emit_newline();
            self.line("/* event loop for periodic reactions */");
            self.line("for (;;) {");
            self.indent += 1;

            // Each `every N ns` reaction gets its own next-fire timestamp.
            // We track a uint64_t monotonic tick counter per reaction.
            for reaction in &module.reactions {
                if let SirTrigger::EveryNs(ns) = reaction.trigger {
                    let var = format!("__next_{}", reaction.id);
                    self.line(&format!("uint64_t {} = {}ULL;", var, ns));
                    let _ = ns; // used below
                }
            }

            // Minimal polling loop: sleep the shortest period, then call all
            // reactions whose deadline has passed.
            // For simplicity (Phase 0) we just call each periodic reaction once
            // per sleep interval.
            //
            // A production scheduler would compute the nearest deadline and
            // sleep exactly that long — that is §5.1 work, deferred to Phase 1.
            let min_ns = module
                .reactions
                .iter()
                .filter_map(|r| if let SirTrigger::EveryNs(ns) = r.trigger { Some(ns) } else { None })
                .min()
                .unwrap_or(1_000_000_000);

            self.line(&format!("__host_sleep_ns({}ULL);", min_ns));
            for reaction in &module.reactions {
                if matches!(reaction.trigger, SirTrigger::EveryNs(_)) {
                    self.line(&format!("{}();", reaction_fn_name(reaction.id)));
                }
            }

            self.indent -= 1;
            self.line("}");
        } else {
            self.line("return 0;");
        }

        self.indent -= 1;
        self.line("}");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    fn line(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.buf.push_str(&indent);
        self.buf.push_str(s);
        self.buf.push('\n');
    }

    fn emit_newline(&mut self) {
        self.buf.push('\n');
    }
}

// ─── Free helpers ─────────────────────────────────────────────────────────────

fn reaction_fn_name(id: usize) -> String {
    format!("__reaction_{}", id)
}

fn trigger_comment(trigger: &SirTrigger) -> String {
    match trigger {
        SirTrigger::SysStart => "reaction: on sys.start".into(),
        SirTrigger::EveryNs(ns) => format!("reaction: every {}ns", ns),
    }
}

fn emit_place(place: &SirPlace) -> String {
    match place {
        SirPlace::Var(name) => name.clone(),
    }
}

fn emit_expr(expr: &SirExpr) -> String {
    match expr {
        SirExpr::Bool(b) => if *b { "1U".into() } else { "0U".into() },
        SirExpr::U64(n) => format!("{}ULL", n),
        SirExpr::Bytes(bytes) => {
            // Bytes as a cast-to-const-pointer string literal.
            let escaped = c_escape_bytes(bytes);
            format!("(const uint8_t *)\"{}\"", escaped)
        }
        SirExpr::Load(name) => name.clone(),
        SirExpr::Not(inner) => format!("(!({}))", emit_expr(inner)),
        SirExpr::BinOp(op, lhs, rhs) => {
            let l = emit_expr(lhs);
            let r = emit_expr(rhs);
            let op_str = match op {
                SirBinOp::Add => "+",
                SirBinOp::Sub => "-",
                SirBinOp::Mul => "*",
                SirBinOp::Div => "/",
                SirBinOp::Rem => "%",
                SirBinOp::And => "&&",
                SirBinOp::Or => "||",
                SirBinOp::EqEq => "==",
                SirBinOp::NotEq => "!=",
                SirBinOp::Lt => "<",
                SirBinOp::Le => "<=",
                SirBinOp::Gt => ">",
                SirBinOp::Ge => ">=",
            };
            format!("({} {} {})", l, op_str, r)
        }
    }
}

fn expr_to_c_literal(expr: &SirExpr) -> String {
    match expr {
        SirExpr::Bool(b) => if *b { "1U".into() } else { "0U".into() },
        SirExpr::U64(n) => format!("{}ULL", n),
        _ => "0".into(),
    }
}

/// Escape a byte slice into a C string literal body (no surrounding quotes).
fn c_escape_bytes(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len());
    for &b in bytes {
        match b {
            b'\n' => s.push_str("\\n"),
            b'\t' => s.push_str("\\t"),
            b'\r' => s.push_str("\\r"),
            b'\\' => s.push_str("\\\\"),
            b'"' => s.push_str("\\\""),
            b'\0' => s.push_str("\\0"),
            0x20..=0x7e => s.push(b as char),
            _ => {
                let _ = write!(s, "\\x{:02x}", b);
            }
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_escape_basics() {
        assert_eq!(c_escape_bytes(b"Hello\n"), "Hello\\n");
        assert_eq!(c_escape_bytes(b"say \"hi\""), "say \\\"hi\\\"");
    }

    #[test]
    fn emit_hello_world() {
        let module = SirModule {
            reactions: vec![SirReaction {
                id: 0,
                trigger: SirTrigger::SysStart,
                body: vec![SirStmt::Intrinsic(SirIntrinsic::HostIoPrintStr(
                    "Hello, World!\n".into(),
                ))],
            }],
            vars: vec![],
        };
        let c = CBackend::new().emit(&module);
        assert!(c.contains("__host_io_print"));
        assert!(c.contains("Hello, World!\\n"));
        assert!(c.contains("int main(void)"));
        assert!(c.contains("__reaction_0();"));
    }
}
